# repo_url: https://github.com/northshorewc/ccr2016
copyright: North Shore Water Commission &copy; 2017 - <a href='http://www.northshorewater.org'><i>visit us at www.northshorewater.org</i></a>
remote_branch: gh-pages
site_url: https://northshorewc.github.io/ccr2016
site_author: Eric Kiefer
site_name: 2016 Annual Water Quality Report
google_analytics: ['UA-93001027-1','auto']
theme: readthedocs
theme_dir: readthedocs-theme
# theme: material
# theme_dir: material-theme
extra_css:
  - css/extra.css
extra_javascript: 
  # - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML-full
  - https://use.fontawesome.com/ccef82ad40.js
  - js/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/jquery.sticky/1.0.4/jquery.sticky.js
markdown_extensions:
  - admonition:
  - def_list:
  - footnotes: 
  - toc:
  - mdx_math:
  # - pymdownx.arithmatex:
pages:
  - Home: index.md
  # - Legal-Ad-NorthShoreNow: publish.md
  # - Additional Lead Information: lead.md